name = "WorkstealingQueues"
uuid = "5de86365-37b3-4156-83c9-8067376b4c4f"
authors = ["Gabriel Baraldi and Valentin Churavy" ]
version = "0.1.0"


[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
